name: Node CI

on: push

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies, run lint analysis and execute tests
      run: |
        npm install
        npm run lint
        npm test
        npm run coverage
      env:
        CI: true
    - name: Upload coverage to QLTY
      uses: qltysh/qlty-action/coverage@v2
      with:
        oidc: true
        files: coverage/lcov.info
