name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies, run lint analysis and execute tests
      run: |
        npm install
        npm run lint
        npm test
        npm run coverage
      env:
        CI: true
    - name: Run QLTY
      uses: qltysh/qlty-action@v1
      with:
        coverage-file: coverage/lcov.info
